In [2]:
import pandas as pd
import numpy as np
import seaborn as sns

In [ ]:
# Nominal / One Hot Encoding -> Binary vector for each of the categories
#example : single, married, separated
# single : 1 0 0
# married : 0 1 0
# separated : 0 0 1

In [3]:
from sklearn.preprocessing import OneHotEncoder
df = pd.DataFrame({"marital_status": ["single", "married", "separated", "single", "married"]})
df

  marital_status
0         single
1        married
2      separated
3         single
4        married

In [7]:
# # creating the one hot encoder object
# encoder = OneHotEncoder(sparse = False)
# encoded_data = encoder.fit_transform(df[["marital_status"]])
# encoded_data = pd.DataFrame(encoded_data, columns = encoder.get_feature_names_out())
# encoded_data

# the above give error 

# Fix 1 — use sparse_output instead of sparse (sklearn 1.2+)
encoder = OneHotEncoder(sparse_output=False)
encoded_data = encoder.fit_transform(df[["marital_status"]])
encoded_data = pd.DataFrame(encoded_data, columns=encoder.get_feature_names_out())
encoded_data

   marital_status_married  marital_status_separated  marital_status_single
0                     0.0                       0.0                    1.0
1                     1.0                       0.0                    0.0
2                     0.0                       1.0                    0.0
3                     0.0                       0.0                    1.0
4                     1.0                       0.0                    0.0

In [9]:
# Fix 2 — convert to dense array explicitly (works on all versions)
encoder = OneHotEncoder()
encoded_data = encoder.fit_transform(df[["marital_status"]]).toarray()
encoded_data = pd.DataFrame(encoded_data, columns=encoder.get_feature_names_out())
encoded_data
#.toarray() converts the sparse matrix to a regular NumPy array regardless of sklearn version — safest approach.

   marital_status_married  marital_status_separated  marital_status_single
0                     0.0                       0.0                    1.0
1                     1.0                       0.0                    0.0
2                     0.0                       1.0                    0.0
3                     0.0                       0.0                    1.0
4                     1.0                       0.0                    0.0

In [10]:
# now lets work on dataset

In [11]:
df = sns.load_dataset("tips")
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [12]:
# days 
df['day'].unique()

['Sun', 'Sat', 'Thur', 'Fri']
Categories (4, object): ['Thur', 'Fri', 'Sat', 'Sun']

In [13]:
encoder = OneHotEncoder(sparse_output=False)
encoded_day = encoder.fit_transform(df[["day"]])
encoded_day = pd.DataFrame(encoded_day, columns= encoder.get_feature_names_out())
encoded_day

     day_Fri  day_Sat  day_Sun  day_Thur
0        0.0      0.0      1.0       0.0
1        0.0      0.0      1.0       0.0
2        0.0      0.0      1.0       0.0
3        0.0      0.0      1.0       0.0
4        0.0      0.0      1.0       0.0
..       ...      ...      ...       ...
239      0.0      1.0      0.0       0.0
240      0.0      1.0      0.0       0.0
241      0.0      1.0      0.0       0.0
242      0.0      1.0      0.0       0.0
243      0.0      0.0      0.0       1.0

[244 rows x 4 columns]

In [14]:
# lebel encoding -> assign a number to each category
from sklearn.preprocessing import LabelEncoder
df = pd.DataFrame({"marital_status": ["single", "married", "separated", "single", "married"]})

label_encoder = LabelEncoder()
encoder_label = label_encoder.fit_transform(df[["marital_status"]])
print(encoder_label)
# convert to dataframe
encoder_label = pd.DataFrame(encoder_label, columns=["marital_status_encoded"])
encoder_label

[2 0 1 2 0]

c:\Users\Naman\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

   marital_status_encoded
0                       2
1                       0
2                       1
3                       2
4                       0

In [16]:
# Ordinal encoding -> assign a number to each category based on order
# example : 
'''
high school : 1
graduate : 2
post graduate : 3
Phd : 4
'''

'\nhigh school : 1\ngraduate : 2\npost graduate : 3\nPhd : 4\n'

In [17]:
from sklearn.preprocessing import OrdinalEncoder
df = pd.DataFrame({"education": ["high school", "graduate", "post graduate", "Phd", "graduate"]})
ordinal_encoder = OrdinalEncoder(categories=[["high school", "graduate", "post graduate", "Phd"]])
encoded_education = ordinal_encoder.fit_transform(df[["education"]])
encoded_education = pd.DataFrame(encoded_education, columns=["education_encoded"])
encoded_education

   education_encoded
0                0.0
1                1.0
2                2.0
3                3.0
4                1.0

In [ ]:
# Target Guided Ordinal Encoding -> assign a number to each category based on the target variable
# Relationship with target variable 
# A lot of unique categories 
# replace the category with mean and median of respective group

In [ ]:
# claude code example

In [19]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

data = {
    'Age':        [25, 34, 28, 45, 31],
    'City':       ['Mumbai', 'Delhi', 'Chennai', 'Mumbai', 'Kolkata'],
    'Gender':     ['Male', 'Female', 'Male', 'Female', 'Male'],
    'Purchased':  ['Yes', 'No', 'Yes', 'Yes', 'No'],
    'Salary':     [35000, 95000, 18000, 75000, 52000]
}
df = pd.DataFrame(data)
df

   Age     City  Gender Purchased  Salary
0   25   Mumbai    Male       Yes   35000
1   34    Delhi  Female        No   95000
2   28  Chennai    Male       Yes   18000
3   45   Mumbai  Female       Yes   75000
4   31  Kolkata    Male        No   52000

In [25]:
#Now apply One Hot Encoding on City and Gender — both nominal, low unique values:

In [24]:
# Step 1 — identify columns to encode
ohe_cols = ['City', 'Gender']

# Step 2 — fit and transform
encoder = OneHotEncoder(sparse_output=False)
encoded_array = encoder.fit_transform(df[ohe_cols])

# Step 3 — convert to DataFrame
encoded_df = pd.DataFrame(encoded_array, columns=encoder.get_feature_names_out())

# Step 4 — drop original columns and join encoded ones
df_encoded = df.drop(columns=ohe_cols)
df_final = pd.concat([df_encoded, encoded_df], axis=1)
df_final

,Age,Purchased,Salary,City_Chennai,City_Delhi,City_Kolkata,City_Mumbai,Gender_Female,Gender_Male
0,25,Yes,35000,0.0,0.0,0.0,1.0,0.0,1.0
1,34,No,95000,0.0,1.0,0.0,0.0,1.0,0.0
2,28,Yes,18000,1.0,0.0,0.0,0.0,0.0,1.0
3,45,Yes,75000,0.0,0.0,0.0,1.0,1.0,0.0
4,31,No,52000,0.0,0.0,1.0,0.0,0.0,1.0

In [26]:
""" 
pd.concat([df1, df2], axis=?)
```

`[df1, df2]` — a **list** of DataFrames to join together.

---

### axis=0 vs axis=1 — The Most Important Part

Think of your DataFrame as a table:
```
axis=0 → vertical direction   (along rows    ↕)
axis=1 → horizontal direction (along columns ↔)
```

Visually:
```
axis = 0  (stacking rows on top of each other)

   df1:          df2:          result:
   A   B         A   B         A   B
   1   2    +    5   6    =    1   2
   3   4         7   8         3   4
                               5   6
                               7   8
```
```
axis = 1  (joining columns side by side)

   df1:          df2:          result:
   A   B         C   D         A   B   C   D
   1   2    +    5   6    =    1   2   5   6
   3   4         7   8         3   4   7   8

"""

' \npd.concat([df1, df2], axis=?)\n```\n\n`[df1, df2]` — a **list** of DataFrames to join together.\n\n---\n\n### axis=0 vs axis=1 — The Most Important Part\n\nThink of your DataFrame as a table:\n```\naxis=0 → vertical direction   (along rows    ↕)\naxis=1 → horizontal direction (along columns ↔)\n```\n\nVisually:\n```\naxis = 0  (stacking rows on top of each other)\n\n   df1:          df2:          result:\n   A   B         A   B         A   B\n   1   2    +    5   6    =    1   2\n   3   4         7   8         3   4\n                               5   6\n                               7   8\n```\n```\naxis = 1  (joining columns side by side)\n\n   df1:          df2:          result:\n   A   B         C   D         A   B   C   D\n   1   2    +    5   6    =    1   2   5   6\n   3   4         7   8         3   4   7   8\n\n'

In [27]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

data = {
    'Age':        [25, 34, 28, 45, 31],
    'City':       ['Mumbai', 'Delhi', 'Chennai', 'Mumbai', 'Kolkata'],
    'Gender':     ['Male', 'Female', 'Male', 'Female', 'Male'],
    'Purchased':  ['Yes', 'No', 'Yes', 'Yes', 'No'],
    'Salary':     [35000, 95000, 18000, 75000, 52000]
}
df = pd.DataFrame(data)

In [28]:
label_encoder = LabelEncoder()
df["Purchased_encoded"] = label_encoder.fit_transform(df["Purchased"])
df[["Purchased", "Purchased_encoded"]]

  Purchased  Purchased_encoded
0       Yes                  1
1        No                  0
2       Yes                  1
3       Yes                  1
4        No                  0

In [32]:
# for multiple columns
binary_cols = ['Purchased', 'Gender']

label_encoder = LabelEncoder()

for col in binary_cols:
    df[col + "_encoded"] = label_encoder.fit_transform(df[col])
df[["Purchased", "Purchased_encoded", "Gender", "Gender_encoded"]]

  Purchased  Purchased_encoded  Gender  Gender_encoded
0       Yes                  1    Male               1
1        No                  0  Female               0
2       Yes                  1    Male               1
3       Yes                  1  Female               0
4        No                  0    Male               1

In [33]:
#ordinal : 
data = {
    'Name':          ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
    'Education':     ['high school', 'graduate', 'phd', 
                      'post graduate', 'graduate'],
    'Experience':    ['junior', 'senior', 'junior', 'lead', 'senior'],
    'Satisfaction':  ['low', 'high', 'medium', 'high', 'low'],
    'Salary':        [35000, 95000, 18000, 75000, 52000]
}
df = pd.DataFrame(data)
df

      Name      Education Experience Satisfaction  Salary
0    Alice    high school     junior          low   35000
1      Bob       graduate     senior         high   95000
2  Charlie            phd     junior       medium   18000
3    David  post graduate       lead         high   75000
4      Eve       graduate     senior          low   52000

In [34]:
from sklearn.preprocessing import OrdinalEncoder

# Define order for EACH ordinal column separately
education_order   = ["high school", "graduate", "post graduate", "phd"]
experience_order  = ["junior", "senior", "lead"]
satisfaction_order = ["low", "medium", "high"]

ordinal_cols = ["Education", "Experience", "Satisfaction"]

ordinal_encoder = OrdinalEncoder(categories=[
    education_order,     # order for Education column
    experience_order,    # order for Experience column
    satisfaction_order   # order for Satisfaction column
])

encoded_array = ordinal_encoder.fit_transform(df[ordinal_cols])
encoded_df = pd.DataFrame(encoded_array, columns=[
    "Education_encoded", "Experience_encoded", "Satisfaction_encoded"
])

# drop originals and join encoded
df_final = pd.concat([df.drop(columns=ordinal_cols), encoded_df], axis=1)
df_final

# ```

# **Result:**
# ```
#       Name  Salary  Education_encoded  Experience_encoded  Satisfaction_encoded
# 0    Alice   35000                0.0                 0.0                   0.0
# 1      Bob   95000                1.0                 1.0                   2.0
# 2  Charlie   18000                3.0                 0.0                   2.0
# 3    David   75000                2.0                 2.0                   2.0
# 4      Eve   52000                1.0                 1.0                   0.0
# ```

# **Mapping happening internally:**
# ```
# Education:    high school=0  graduate=1  post graduate=2  phd=3
# Experience:   junior=0       senior=1    lead=2
# Satisfaction: low=0          medium=1    high=2

,Name,Salary,Education_encoded,Experience_encoded,Satisfaction_encoded
0,Alice,35000,0.0,0.0,0.0
1,Bob,95000,1.0,1.0,2.0
2,Charlie,18000,3.0,0.0,1.0
3,David,75000,2.0,2.0,2.0
4,Eve,52000,1.0,1.0,0.0

In [35]:
#📌 6. Target Guided Ordinal Encoding
import pandas as pd
import numpy as np

data = {
    'Name':       ['Alice','Bob','Charlie','David','Eve',
                   'Frank','Grace','Hank','Ivy','Jack'],
    'Job_Title':  ['Cashier','Data Scientist','Analyst','Manager','Sales Exec',
                   'Analyst','Manager','Cashier','Data Scientist','Sales Exec'],
    'City':       ['Mumbai','Delhi','Mumbai','Chennai','Delhi',
                   'Kolkata','Mumbai','Delhi','Chennai','Kolkata'],
    'Purchased':  ['Yes','No','Yes','Yes','No',
                   'Yes','No','Yes','No','Yes'],
    'Salary':     [18000, 95000, 52000, 75000, 35000,
                   55000, 78000, 20000, 92000, 38000]
}
df = pd.DataFrame(data)
df

      Name       Job_Title     City Purchased  Salary
0    Alice         Cashier   Mumbai       Yes   18000
1      Bob  Data Scientist    Delhi        No   95000
2  Charlie         Analyst   Mumbai       Yes   52000
3    David         Manager  Chennai       Yes   75000
4      Eve      Sales Exec    Delhi        No   35000
5    Frank         Analyst  Kolkata       Yes   55000
6    Grace         Manager   Mumbai        No   78000
7     Hank         Cashier    Delhi       Yes   20000
8      Ivy  Data Scientist  Chennai        No   92000
9     Jack      Sales Exec  Kolkata       Yes   38000

In [36]:
#Step 1 — Calculate Mean Salary per Job Title
mean_salary_by_job = df.groupby("Job_Title")["Salary"].mean()
print(mean_salary_by_job)

Job_Title
Analyst           53500.0
Cashier           19000.0
Data Scientist    93500.0
Manager           76500.0
Sales Exec        36500.0
Name: Salary, dtype: float64

In [37]:
"""
How groupby() works:

df.groupby("Job_Title")["Salary"].mean()
```
```
groupby("Job_Title")  →  splits the DataFrame into groups:

Group 1 — Cashier:
   Alice   18000
   Hank    20000

Group 2 — Data Scientist:
   Bob     95000
   Ivy     92000

Group 3 — Analyst:
   Charlie 52000
   Frank   55000
...
```
```
["Salary"]  →  select only Salary column from each group
.mean()     →  calculate mean of Salary for each group
```

**Result:**
```
Job_Title
Analyst           53500.0
Cashier           19000.0
Data Scientist    93500.0
Manager           76500.0
Sales Exec        36500.0
"""

'\nHow groupby() works:\n\ndf.groupby("Job_Title")["Salary"].mean()\n```\n```\ngroupby("Job_Title")  →  splits the DataFrame into groups:\n\nGroup 1 — Cashier:\n   Alice   18000\n   Hank    20000\n\nGroup 2 — Data Scientist:\n   Bob     95000\n   Ivy     92000\n\nGroup 3 — Analyst:\n   Charlie 52000\n   Frank   55000\n...\n```\n```\n["Salary"]  →  select only Salary column from each group\n.mean()     →  calculate mean of Salary for each group\n```\n\n**Result:**\n```\nJob_Title\nAnalyst           53500.0\nCashier           19000.0\nData Scientist    93500.0\nManager           76500.0\nSales Exec        36500.0\n'

In [38]:
#Step 2 — Create Ordinal Rank Based on Mean
# sort by mean salary and assign rank 0, 1, 2, 3, 4
mean_salary_sorted = mean_salary_by_job.sort_values()
job_title_rank = {job: rank for rank, job in enumerate(mean_salary_sorted.index)}
print(job_title_rank)

""" 
Breaking down enumerate():
mean_salary_sorted.index = ['Cashier', 'Sales Exec', 'Analyst', 'Manager', 'Data Scientist']
#                            lowest mean                                      highest mean

enumerate(mean_salary_sorted.index)
# gives: (0, 'Cashier'), (1, 'Sales Exec'), (2, 'Analyst'), (3, 'Manager'), (4, 'Data Scientist')
#         rank  job                rank  job
"""

{'Cashier': 0, 'Sales Exec': 1, 'Analyst': 2, 'Manager': 3, 'Data Scientist': 4}

" \nBreaking down enumerate():\nmean_salary_sorted.index = ['Cashier', 'Sales Exec', 'Analyst', 'Manager', 'Data Scientist']\n#                            lowest mean                                      highest mean\n\nenumerate(mean_salary_sorted.index)\n# gives: (0, 'Cashier'), (1, 'Sales Exec'), (2, 'Analyst'), (3, 'Manager'), (4, 'Data Scientist')\n#         rank  job                rank  job\n"

In [39]:
# same as writing:
job_title_rank = {}
for rank, job in enumerate(mean_salary_sorted.index):
    job_title_rank[job] = rank

In [41]:
#Step 3 — Map the Rank Back to the Column
df["Job_Title_encoded"] = df["Job_Title"].map(job_title_rank)
df[["Job_Title", "Salary", "Job_Title_encoded"]]

""" 
How .map() works:

df["Job_Title"].map(job_title_rank)
```
Goes through every value in `Job_Title` column, looks it up in the dictionary, and replaces it with the corresponding rank:
```
Alice   →  Cashier         →  look up in dict  →  0
Bob     →  Data Scientist  →  look up in dict  →  4
Charlie →  Analyst         →  look up in dict  →  2
David   →  Manager         →  look up in dict  →  3
Eve     →  Sales Exec      →  look up in dict  →  1
...
```

**Result:**
```
     Job_Title   Salary  Job_Title_encoded
0      Cashier    18000                  0
1   Data Sci...   95000                  4
2      Analyst    52000                  2
3      Manager    75000                  3
4   Sales Exec    35000                  1
5      Analyst    55000                  2
6      Manager    78000                  3
7      Cashier    20000                  0
8   Data Sci...   92000                  4
9   Sales Exec    38000                  1
"""

' \nHow .map() works:\n\ndf["Job_Title"].map(job_title_rank)\n```\nGoes through every value in `Job_Title` column, looks it up in the dictionary, and replaces it with the corresponding rank:\n```\nAlice   →  Cashier         →  look up in dict  →  0\nBob     →  Data Scientist  →  look up in dict  →  4\nCharlie →  Analyst         →  look up in dict  →  2\nDavid   →  Manager         →  look up in dict  →  3\nEve     →  Sales Exec      →  look up in dict  →  1\n...\n```\n\n**Result:**\n```\n     Job_Title   Salary  Job_Title_encoded\n0      Cashier    18000                  0\n1   Data Sci...   95000                  4\n2      Analyst    52000                  2\n3      Manager    75000                  3\n4   Sales Exec    35000                  1\n5      Analyst    55000                  2\n6      Manager    78000                  3\n7      Cashier    20000                  0\n8   Data Sci...   92000                  4\n9   Sales Exec    38000                  1\n'

In [42]:
from sklearn.preprocessing import OneHotEncoder, LabelEncoder, OrdinalEncoder

df_processed = df.copy()

# 1 — Target Guided Ordinal Encoding on Job_Title (high cardinality, nominal)
mean_by_job   = df_processed.groupby("Job_Title")["Salary"].mean().sort_values()
job_rank      = {job: rank for rank, job in enumerate(mean_by_job.index)}
df_processed["Job_Title_encoded"] = df_processed["Job_Title"].map(job_rank)

# 2 — One Hot Encoding on City (low cardinality, nominal)
ohe = OneHotEncoder(sparse_output=False, drop="first")
city_encoded = ohe.fit_transform(df_processed[["City"]])
city_df = pd.DataFrame(city_encoded, columns=ohe.get_feature_names_out())

# 3 — Label Encoding on Purchased (binary)
le = LabelEncoder()
df_processed["Purchased_encoded"] = le.fit_transform(df_processed["Purchased"])

# 4 — Drop original columns, join all encoded
df_processed = df_processed.drop(columns=["Job_Title", "City", "Purchased", "Name"])
df_final = pd.concat([df_processed, city_df], axis=1)
df_final

,Salary,Job_Title_encoded,Purchased_encoded,City_Delhi,City_Kolkata,City_Mumbai
0,18000,0,1,0.0,0.0,1.0
1,95000,4,0,1.0,0.0,0.0
2,52000,2,1,0.0,0.0,1.0
3,75000,3,1,0.0,0.0,0.0
4,35000,1,0,1.0,0.0,0.0
5,55000,2,1,0.0,1.0,0.0
6,78000,3,0,0.0,0.0,1.0
7,20000,0,1,1.0,0.0,0.0
8,92000,4,0,0.0,0.0,0.0
9,38000,1,1,0.0,1.0,0.0