____________________________________________________________________________________________________________

In [7]:
import pandas as pd
df = pd.DataFrame({"Data science is an interdisciplinary field that combines statistics, computer science, and domain knowledge to extract meaningful insights from data. Data scientists use this information to identify patterns, build predictive models, and help organizations make data-driven decisions. It involves gathering and analyzing large datasets to solve problems and forecast future trends. "}, columns=['Description'])
print(df)

                                                                                                                                                                                                                                                                                                                                                                                      Description
0  Data science is an interdisciplinary field that combines statistics, computer science, and domain knowledge to extract meaningful insights from data. Data scientists use this information to identify patterns, build predictive models, and help organizations make data-driven decisions. It involves gathering and analyzing large datasets to solve problems and forecast future trends.

In [8]:
# in above result you can see its not showing full text so to show full text we can use below code
pd.set_option('display.max_colwidth', None) 
print(df)

                                                                                                                                                                                                                                                                                                                                                                                      Description
0  Data science is an interdisciplinary field that combines statistics, computer science, and domain knowledge to extract meaningful insights from data. Data scientists use this information to identify patterns, build predictive models, and help organizations make data-driven decisions. It involves gathering and analyzing large datasets to solve problems and forecast future trends.

In [9]:
df['description_length'] = df['Description'].apply(len)
print(df)

                                                                                                                                                                                                                                                                                                                                                                                      Description  \
0  Data science is an interdisciplinary field that combines statistics, computer science, and domain knowledge to extract meaningful insights from data. Data scientists use this information to identify patterns, build predictive models, and help organizations make data-driven decisions. It involves gathering and analyzing large datasets to solve problems and forecast future trends.

   description_length
0                 382

In [12]:
#let say we have to find no of words 
# for string : 
a = "I am Parth"
print(a.split())          # counts total characters including spaces
print(len(a.split()))  # splits the string into words and counts them

['I', 'am', 'Parth']
3

In [13]:
df

,Description,description_length
0,"Data science is an interdisciplinary field that combines statistics, computer science, and domain knowledge to extract meaningful insights from data. Data scientists use this information to identify patterns, build predictive models, and help organizations make data-driven decisions. It involves gathering and analyzing large datasets to solve problems and forecast future trends.",382

In [16]:
df['Description_word_count'] = df['Description'].apply(lambda x: len(x.split()))
df

,Description,description_length,Description_word_count
0,"Data science is an interdisciplinary field that combines statistics, computer science, and domain knowledge to extract meaningful insights from data. Data scientists use this information to identify patterns, build predictive models, and help organizations make data-driven decisions. It involves gathering and analyzing large datasets to solve problems and forecast future trends.",382,51

_______________________________________________________________________________________________________________________________

In [19]:
data = {
    "text" : [   # text is list of strings 
        'Hello Data Science',  # string 1
        'I love Machine Learning', # string 2
        'I read Data Science books', # string 3
    ]
}

df = pd.DataFrame(data)

In [20]:
df

                        text
0         Hello Data Science
1    I love Machine Learning
2  I read Data Science books

In [22]:
# now let says we have to lower case all the strings in text column 
df['text_lower'] = df['text'].apply(lambda x:x.lower())   # instead of apply(lambda x:x.lower()) we can also use .str.lower()
df

                        text                 text_lower
0         Hello Data Science         hello data science
1    I love Machine Learning    i love machine learning
2  I read Data Science books  i read data science books

In [32]:
df['text_upper'] =df['text'].str.upper()
df

,text,text_lower,text_upper
0,Hello Data Science,hello data science,HELLO DATA SCIENCE
1,I love Machine Learning,i love machine learning,I LOVE MACHINE LEARNING
2,I read Data Science books,i read data science books,I READ DATA SCIENCE BOOKS

In [ ]:
# # lets say we have to drop column start_witth 'H'
# df = df.drop(columns=['starts_with_H'])
# df

,text,text_lower,text_upper
0,Hello Data Science,hello data science,HELLO DATA SCIENCE
1,I love Machine Learning,i love machine learning,I LOVE MACHINE LEARNING
2,I read Data Science books,i read data science books,I READ DATA SCIENCE BOOKS

In [36]:
print(df['text'].str.startswith('H'))
# You do NOT want the whole Series.
# You want only the first value.
print(df['text'].iloc[0].startswith('H'))

0     True
1    False
2    False
Name: text, dtype: bool
True

_____________________________________________________________________________________________________________________________________

In [37]:
df3 = pd.DataFrame({
    'a': [1,2,4,5,6],
    'b': [4,5,6,7,8]
})
df3

   a  b
0  1  4
1  2  5
2  4  6
3  5  7
4  6  8

In [38]:
# let say we have to multiply columb a by 5 
df3['a_multiple'] = df3['a']*5 
df3

   a  b  a_multiple
0  1  4           5
1  2  5          10
2  4  6          20
3  5  7          25
4  6  8          30

_________________________________________________________________________________________________
rolling function

In [39]:
df4 = pd.DataFrame({
    'a': [1,2,3,4,5,6,7,8,9]
})
df4

   a
0  1
1  2
2  3
3  4
4  5
5  6
6  7
7  8
8  9

In [40]:
df4.rolling(window=2).mean()  # here window=3 means it will take 2 values at a time and calculate mean

     a
0  NaN
1  1.5
2  2.5
3  3.5
4  4.5
5  5.5
6  6.5
7  7.5
8  8.5

In [ ]:
df4.rolling(window=3).sum() # here window=3 means it will take 3 values at a time and calculate sum
# first 2 values will be NaN because there are not enough values to fill the window of 3

      a
2   6.0
3   9.0
4  12.0
5  15.0
6  18.0
7  21.0
8  24.0

In [46]:
df4.rolling(window=3).sum().dropna() # to drop NaN values

      a
2   6.0
3   9.0
4  12.0
5  15.0
6  18.0
7  21.0
8  24.0

In [50]:
#typecasting 
df4['a_float'] = df4['a'].astype(float)
df4

   a  a_float
0  1      1.0
1  2      2.0
2  3      3.0
3  4      4.0
4  5      5.0
5  6      6.0
6  7      7.0
7  8      8.0
8  9      9.0

In [53]:
import numpy as np
df_random = pd.DataFrame({
    'a': [1,2,3,4,5,6,7,8,9],
    'b': [4,3,7,5,2,8,1,9,6]
})
df_random

   a  b
0  1  4
1  2  3
2  3  7
3  4  5
4  5  2
5  6  8
6  7  1
7  8  9
8  9  6

In [55]:
df_random['group'] = np.random.choice(['a','b'], size=9)
df_random

   a  b group
0  1  4     a
1  2  3     a
2  3  7     a
3  4  5     a
4  5  2     a
5  6  8     b
6  7  1     a
7  8  9     b
8  9  6     b

In [ ]:

df_random.groupby('group')['a'].sum() 
''' 
✅ 1) groupby('group')

Splits the DataFrame into separate mini-tables based on the values in the "group" column.

If "group" contains 'a' and 'b', you now have:

one group containing all rows where group == 'a'

one group containing all rows where group == 'b'

✅ 2) ['a']

From each group, select only column 'a'.
Column 'b' is ignored completely.

✅ 3) .sum()

For each group, add all the values in column 'a'.
'''

group
a    22
b    23
Name: a, dtype: int64

In [ ]:
#let say we have to do rolling sum on groupby
df_random.groupby('group')['a'].rolling(window=2).sum()

group
a      0     NaN
       1     3.0
       2     5.0
       3     7.0
       4     9.0
       6    12.0
b      5     NaN
       7    14.0
       8    17.0
Name: a, dtype: float64

In [61]:
# cumulative sum 
df_random.a.cumsum()

0     1
1     3
2     6
3    10
4    15
5    21
6    28
7    36
8    45
Name: a, dtype: int64

________________________________________________________________________________________________________________________________
date and time

In [67]:
import pandas as pd

df_dates = pd.DataFrame({
    "date": [
        "2024-01-01",
        "2024-01-05",
        "2024-02-10",
        "2024-03-15",
        "2024-04-01",
        "2024-04-20"
    ]
})

# # Convert strings to proper datetime type (recommended)
# df_dates['date'] = pd.to_datetime(df_dates['date'])

df_dates

         date
0  2024-01-01
1  2024-01-05
2  2024-02-10
3  2024-03-15
4  2024-04-01
5  2024-04-20

In [69]:
print(df.info())
print(f'\n\n {df.dtypes}')
# you will be find out it is string ( object ), not in datetime format

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   text        3 non-null      object
 1   text_lower  3 non-null      object
 2   text_upper  3 non-null      object
dtypes: object(3)
memory usage: 204.0+ bytes
None


 text          object
text_lower    object
text_upper    object
dtype: object

In [70]:
df_dates['date_updated'] = pd.to_datetime(df_dates['date'])
df_dates

         date date_updated
0  2024-01-01   2024-01-01
1  2024-01-05   2024-01-05
2  2024-02-10   2024-02-10
3  2024-03-15   2024-03-15
4  2024-04-01   2024-04-01
5  2024-04-20   2024-04-20

In [71]:
# lets access year ,month ,day
df_dates['year'] = df_dates['date_updated'].dt.year
df_dates['month'] = df_dates['date_updated'].dt.month
df_dates['day'] = df_dates['date_updated'].dt.day

In [72]:
df_dates

         date date_updated  year  month  day
0  2024-01-01   2024-01-01  2024      1    1
1  2024-01-05   2024-01-05  2024      1    5
2  2024-02-10   2024-02-10  2024      2   10
3  2024-03-15   2024-03-15  2024      3   15
4  2024-04-01   2024-04-01  2024      4    1
5  2024-04-20   2024-04-20  2024      4   20

In [73]:
# lets use date_range to create a date range
range_date = pd.date_range(start='2024-01-01', end='2024-01-10', freq = 'D')
range_date

DatetimeIndex(['2024-01-01', '2024-01-02', '2024-01-03', '2024-01-04',
               '2024-01-05', '2024-01-06', '2024-01-07', '2024-01-08',
               '2024-01-09', '2024-01-10'],
              dtype='datetime64[ns]', freq='D')

In [74]:
# lets fetch hourly date range 
hour_data = pd.date_range(start='2024-01-01', end = '2024-01-02', freq = 'H')
hour_data

C:\Users\Naman\AppData\Local\Temp\ipykernel_14680\2973192099.py:2: FutureWarning: 'H' is deprecated and will be removed in a future version, please use 'h' instead.
  hour_data = pd.date_range(start='2024-01-01', end = '2024-01-02', freq = 'H')

DatetimeIndex(['2024-01-01 00:00:00', '2024-01-01 01:00:00',
               '2024-01-01 02:00:00', '2024-01-01 03:00:00',
               '2024-01-01 04:00:00', '2024-01-01 05:00:00',
               '2024-01-01 06:00:00', '2024-01-01 07:00:00',
               '2024-01-01 08:00:00', '2024-01-01 09:00:00',
               '2024-01-01 10:00:00', '2024-01-01 11:00:00',
               '2024-01-01 12:00:00', '2024-01-01 13:00:00',
               '2024-01-01 14:00:00', '2024-01-01 15:00:00',
               '2024-01-01 16:00:00', '2024-01-01 17:00:00',
               '2024-01-01 18:00:00', '2024-01-01 19:00:00',
               '2024-01-01 20:00:00', '2024-01-01 21:00:00',
               '2024-01-01 22:00:00', '2024-01-01 23:00:00',
               '2024-01-02 00:00:00'],
              dtype='datetime64[ns]', freq='h')

In [75]:
# current time 
pd.Timestamp.now()

Timestamp('2025-12-04 12:46:50.089802')

In [76]:
# lets check the execution/run time of a code snippet

start = pd.Timestamp.now()
for i in range(1000000):
    pass
end = pd.Timestamp.now()
print("Execution Time:", end - start)

Execution Time: 0 days 00:00:00.070002

In [77]:
# using import time 
import time
start_time = time.time()
for i in range(1000000):
    pass
end_time = time.time()
print("Execution Time:", end_time - start_time)

Execution Time: 0.05699968338012695

In [78]:
# using time.perf_counter()
start_perf = time.perf_counter()
for i in range(1000000):
    pass
end_perf = time.perf_counter()
print("Execution Time:", end_perf - start_perf)

Execution Time: 0.07153590000234544

In [83]:
from datetime import datetime
date = '2024-01-01'
date = datetime.strptime(date, '%Y-%m-%d')
date

datetime.datetime(2024, 1, 1, 0, 0)

In [84]:
print(date)

2024-01-01 00:00:00

In [85]:
df = pd.read_excel('tesla_mock_data.xlsx')
df

         Date    Open    High     Low   Close  Adj Close   Volume
0  2023-01-01   97.49  100.90   96.90  100.53     100.53  2847191
1  2023-01-02  109.01  111.84  106.60  107.86     107.86  2471091
2  2023-01-03  104.64  107.96  103.20  103.89     103.89  1668234
3  2023-01-04  101.97  105.15   99.94  102.49     102.49  1378480
4  2023-01-05   93.12   95.41   89.90   95.33      95.33  3129863
5  2023-01-06   93.12   96.39   91.87   92.96      92.96  1791971
6  2023-01-07   91.16   91.93   89.43   91.11      91.11  1501157
7  2023-01-08  107.32  108.41  104.55  107.49     107.49  1184423
8  2023-01-09  102.02  102.66  100.83  101.26     101.26  3613501
9  2023-01-10  104.16  105.64  103.43  105.04     105.04  2752290
10 2023-01-11   90.41   92.08   89.04   90.16      90.16  1912495
11 2023-01-12  109.40  110.71  108.42  109.87     109.87  4803645
12 2023-01-13  106.65  109.64  103.36  107.34     107.34  3921944
13 2023-01-14   94.25   95.82   91.33   93.74      93.74  2785954
14 2023-01-15   93.64   94.98   91.24   91.58      91.58  1133272
15 2023-01-16   93.67   95.80   90.56   94.94      94.94  1767836
16 2023-01-17   96.08   97.00   93.17   94.40      94.40  4083153
17 2023-01-18  100.50  103.41   99.44  100.18     100.18  3799487
18 2023-01-19   98.64   99.36   95.46   95.62      95.62  3904941
19 2023-01-20   95.82   99.28   93.70   97.00      97.00  4789137
20 2023-01-21  102.24  105.06   99.32  103.21     103.21  2126081
21 2023-01-22   92.79   93.89   89.60   89.67      89.67  3100021
22 2023-01-23   95.84   96.36   94.39   95.40      95.40  1781474
23 2023-01-24   97.33  100.28   96.50   97.36      97.36  3551503
24 2023-01-25   99.12  101.74   97.94  100.39     100.39  2360828
25 2023-01-26  105.70  108.39  103.92  104.70     104.70  3733736
26 2023-01-27   93.99   96.80   91.04   95.02      95.02  1618467
27 2023-01-28  100.28  101.00   97.20   98.67      98.67  2138848
28 2023-01-29  101.85  103.43  101.33  103.30     103.30  3135619
29 2023-01-30   90.93   91.78   88.90   89.30      89.30  4955488
30 2023-01-31  102.15  105.24  100.40  102.05     102.05  4133837
31 2023-02-01   93.41   95.78   92.24   92.64      92.64  1877844
32 2023-02-02   91.30   92.79   90.44   92.61      92.61  1480047
33 2023-02-03  108.98  109.67  107.47  109.40     109.40  2707923
34 2023-02-04  109.31  110.74  105.98  107.21     107.21  2107447
35 2023-02-05  106.17  107.65  104.70  106.65     106.65  1939903
36 2023-02-06   96.09   98.78   94.03   97.91      97.91  1128391
37 2023-02-07   91.95   94.36   89.34   92.13      92.13  3536582
38 2023-02-08  103.68  106.84  102.09  104.61     104.61  2017026
39 2023-02-09   98.80  100.72   95.38   96.67      96.67  2659280
40 2023-02-10   92.44   93.30   89.05   89.45      89.45  2905279
41 2023-02-11   99.90  102.54   98.64  102.14     102.14  4976224
42 2023-02-12   90.69   93.47   88.70   92.99      92.99  3353839
43 2023-02-13  108.19  110.37  106.79  109.06     109.06  4871179
44 2023-02-14   95.18   97.99   93.83   95.24      95.24  1107450
45 2023-02-15  103.25  105.23  102.64  103.54     103.54  3269042
46 2023-02-16   96.23   98.30   93.90   97.09      97.09  3535893
47 2023-02-17  100.40  102.18   98.39  101.79     101.79  3379126
48 2023-02-18  100.93  101.51  100.28  101.37     101.37  2983509
49 2023-02-19   93.70   94.52   92.36   94.04      94.04  4545837

In [90]:
# 1. Convert to datetime
df['Date'] = pd.to_datetime(df['Date'])

# 2. Set it as index
df = df.set_index('Date')

df

              Open    High     Low   Close  Adj Close   Volume
Date
2023-01-01   97.49  100.90   96.90  100.53     100.53  2847191
2023-01-02  109.01  111.84  106.60  107.86     107.86  2471091
2023-01-03  104.64  107.96  103.20  103.89     103.89  1668234
2023-01-04  101.97  105.15   99.94  102.49     102.49  1378480
2023-01-05   93.12   95.41   89.90   95.33      95.33  3129863
2023-01-06   93.12   96.39   91.87   92.96      92.96  1791971
2023-01-07   91.16   91.93   89.43   91.11      91.11  1501157
2023-01-08  107.32  108.41  104.55  107.49     107.49  1184423
2023-01-09  102.02  102.66  100.83  101.26     101.26  3613501
2023-01-10  104.16  105.64  103.43  105.04     105.04  2752290
2023-01-11   90.41   92.08   89.04   90.16      90.16  1912495
2023-01-12  109.40  110.71  108.42  109.87     109.87  4803645
2023-01-13  106.65  109.64  103.36  107.34     107.34  3921944
2023-01-14   94.25   95.82   91.33   93.74      93.74  2785954
2023-01-15   93.64   94.98   91.24   91.58      91.58  1133272
2023-01-16   93.67   95.80   90.56   94.94      94.94  1767836
2023-01-17   96.08   97.00   93.17   94.40      94.40  4083153
2023-01-18  100.50  103.41   99.44  100.18     100.18  3799487
2023-01-19   98.64   99.36   95.46   95.62      95.62  3904941
2023-01-20   95.82   99.28   93.70   97.00      97.00  4789137
2023-01-21  102.24  105.06   99.32  103.21     103.21  2126081
2023-01-22   92.79   93.89   89.60   89.67      89.67  3100021
2023-01-23   95.84   96.36   94.39   95.40      95.40  1781474
2023-01-24   97.33  100.28   96.50   97.36      97.36  3551503
2023-01-25   99.12  101.74   97.94  100.39     100.39  2360828
2023-01-26  105.70  108.39  103.92  104.70     104.70  3733736
2023-01-27   93.99   96.80   91.04   95.02      95.02  1618467
2023-01-28  100.28  101.00   97.20   98.67      98.67  2138848
2023-01-29  101.85  103.43  101.33  103.30     103.30  3135619
2023-01-30   90.93   91.78   88.90   89.30      89.30  4955488
2023-01-31  102.15  105.24  100.40  102.05     102.05  4133837
2023-02-01   93.41   95.78   92.24   92.64      92.64  1877844
2023-02-02   91.30   92.79   90.44   92.61      92.61  1480047
2023-02-03  108.98  109.67  107.47  109.40     109.40  2707923
2023-02-04  109.31  110.74  105.98  107.21     107.21  2107447
2023-02-05  106.17  107.65  104.70  106.65     106.65  1939903
2023-02-06   96.09   98.78   94.03   97.91      97.91  1128391
2023-02-07   91.95   94.36   89.34   92.13      92.13  3536582
2023-02-08  103.68  106.84  102.09  104.61     104.61  2017026
2023-02-09   98.80  100.72   95.38   96.67      96.67  2659280
2023-02-10   92.44   93.30   89.05   89.45      89.45  2905279
2023-02-11   99.90  102.54   98.64  102.14     102.14  4976224
2023-02-12   90.69   93.47   88.70   92.99      92.99  3353839
2023-02-13  108.19  110.37  106.79  109.06     109.06  4871179
2023-02-14   95.18   97.99   93.83   95.24      95.24  1107450
2023-02-15  103.25  105.23  102.64  103.54     103.54  3269042
2023-02-16   96.23   98.30   93.90   97.09      97.09  3535893
2023-02-17  100.40  102.18   98.39  101.79     101.79  3379126
2023-02-18  100.93  101.51  100.28  101.37     101.37  2983509
2023-02-19   93.70   94.52   92.36   94.04      94.04  4545837

In [91]:
# 3. Now resample monthly
df['Close'].resample('M').mean()

C:\Users\Naman\AppData\Local\Temp\ipykernel_14680\4265386557.py:2: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  df['Close'].resample('M').mean()

Date
2023-01-31    98.769677
2023-02-28    99.291579
Freq: ME, Name: Close, dtype: float64