In [30]:
import pandas as pd
df1 = pd.read_csv("titanic.csv")
print(df1.head())

   survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third
1         1       1  female  38.0      1      0  71.2833        C  First
2         1       3  female  26.0      0      0   7.9250        S  Third
3         1       1  female  35.0      1      0  53.1000        S  First
4         0       3    male  35.0      0      0   8.0500        S  Third

     who  adult_male deck  embark_town alive  alone
0    man        True  NaN  Southampton    no  False
1  woman       False    C    Cherbourg   yes  False
2  woman       False  NaN  Southampton   yes   True
3  woman       False    C  Southampton   yes  False
4    man        True  NaN  Southampton    no   True

In [31]:
df1[0:100] # first 100 rows >> similar as string slicing

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,0,3,male,NaN,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
96,0,1,male,71.0,0,0,34.6542,C,First,man,True,A,Cherbourg,no,True
97,1,1,male,23.0,0,1,63.3583,C,First,man,True,D,Cherbourg,yes,False
98,1,2,female,34.0,0,1,23.0000,S,Second,woman,False,NaN,Southampton,yes,False
99,0,2,male,34.0,1,0,26.0000,S,Second,man,True,NaN,Southampton,no,False

In [32]:
#every fifth row 
df1[0:100:5]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
10,1,3,female,4.0,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False
15,1,2,female,55.0,0,0,16.0000,S,Second,woman,False,NaN,Southampton,yes,True
20,0,2,male,35.0,0,0,26.0000,S,Second,man,True,NaN,Southampton,no,True
25,1,3,female,38.0,1,5,31.3875,S,Third,woman,False,NaN,Southampton,yes,False
30,0,1,male,40.0,0,0,27.7208,C,First,man,True,NaN,Cherbourg,no,True
35,0,1,male,42.0,1,0,52.0000,S,First,man,True,NaN,Southampton,no,False
40,0,3,female,40.0,1,0,9.4750,S,Third,woman,False,NaN,Southampton,no,False
45,0,3,male,NaN,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
50,0,3,male,7.0,4,1,39.6875,S,Third,child,False,NaN,Southampton,no,False
55,1,1,male,NaN,0,0,35.5000,S,First,man,True,C,Southampton,yes,True
60,0,3,male,22.0,0,0,7.2292,C,Third,man,True,NaN,Cherbourg,no,True
65,1,3,male,NaN,1,1,15.2458,C,Third,man,True,NaN,Cherbourg,yes,False
70,0,2,male,32.0,0,0,10.5000,S,Second,man,True,NaN,Southampton,no,True
75,0,3,male,25.0,0,0,7.6500,S,Third,man,True,F,Southampton,no,True
80,0,3,male,22.0,0,0,9.0000,S,Third,man,True,NaN,Southampton,no,True
85,1,3,female,33.0,3,0,15.8500,S,Third,woman,False,NaN,Southampton,yes,False
90,0,3,male,29.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
95,0,3,male,NaN,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [33]:
# accessing rows and columns of dataframe >> implicit/integer/internal indexing  explecit or named indexing

In [34]:
#Implesit indexing
#iloc[row_indexer , column_indexer]
df1.iloc[0:5 , 0:3]  # first 5 rows and first 3 columns

   survived  pclass     sex
0         0       3    male
1         1       1  female
2         1       3  female
3         1       1  female
4         0       3    male

In [35]:
# Explicit indexing
#loc[row_indexer , column_indexer]
print(df1.loc[0:4 , ["age" , "fare"]])  # first 5 rows and age , fare columns
print("\n \n \n")
print(list(df1.loc[0:4 , ["age" , "fare"]] .itertuples()))

    age     fare
0  22.0   7.2500
1  38.0  71.2833
2  26.0   7.9250
3  35.0  53.1000
4  35.0   8.0500




[Pandas(Index=0, age=22.0, fare=7.25), Pandas(Index=1, age=38.0, fare=71.2833), Pandas(Index=2, age=26.0, fare=7.925), Pandas(Index=3, age=35.0, fare=53.1), Pandas(Index=4, age=35.0, fare=8.05)]

In [36]:

series_one = pd.Series(list(df1['age'][2:5]), index=['a', 'b', 'c'])
series_two = pd.Series(list(df1['age'][5:8]), index = ['row5', 'row6', 'row7'])
print(series_one)
print("\n")
print(series_two)

# concatenate two series: >> series with different indexes and dataferame can not be concatenated directly using '+'
# if you keep the indexes same then it will work
series_three = pd.Series(list(df1['age'][2:5]), index=['row5', 'row6', 'row7'])
print("\n")
print(series_three)
print("\n")
print(series_two + series_three)  # it will add values of same index and for different index it will give NaN


# DOUBT: Why df1['age'][2:5] and not df1[2:5]['age'] ?
# SOL: Both work. df1['age'][2:5] means — get age column first, then slice rows 2,3,4 from it.
#      df1[2:5]['age'] means — slice rows first, then get age column. Same result.

# DOUBT: Why no loc here ?
# SOL: loc is for precise row+column selection together. Here we just need a quick slice of one column.
#      loc equivalent would be >> df1.loc[2:4, 'age'] — same result but more verbose.

# DOUBT: Why list() is used ?
# SOL: df1['age'][2:5] returns a Series (with index 2,3,4).
#      list() converts it to a plain Python list [26.0, 35.0, 35.0]
#      so that when we create a new Series with custom index ['a','b','c'], there is no index conflict.

# DOUBT: Why df1['age'][2:5] is considered chained indexing and is it bad ?
# SOL: Yes, [][] is called chained indexing. It can cause SettingWithCopyWarning in some cases.
#      For reading data it is fine, but for modifying data always use loc >> df1.loc[2:4, 'age'] = value

a    26.0
b    35.0
c    35.0
dtype: float64


row5     NaN
row6    54.0
row7     2.0
dtype: float64


row5    26.0
row6    35.0
row7    35.0
dtype: float64


row5     NaN
row6    89.0
row7    37.0
dtype: float64

In [37]:
#drop rows and columns
# by default if you drop anything pandas assume you are dropping rows axis=0

import pandas as pd
df2 = pd.read_csv("titanic.csv")
print(df2.head())
print("\n")

# lets say we have to drop 'who' column 
# df2.drop("who") => gives you error because by default it will try to drop row with index 'who' which is not present
# to drop 'who' column we have to do axix = 1 
df2.drop("who" , axis = 1 , inplace = True)  # inplace = True means changes will be made in original dataframe
# so => axis = 0 >> rows
#    => axis = 1 >> columns
# inplace = True >> changes will be made in original dataframe
print(df2.head())

   survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third
1         1       1  female  38.0      1      0  71.2833        C  First
2         1       3  female  26.0      0      0   7.9250        S  Third
3         1       1  female  35.0      1      0  53.1000        S  First
4         0       3    male  35.0      0      0   8.0500        S  Third

     who  adult_male deck  embark_town alive  alone
0    man        True  NaN  Southampton    no  False
1  woman       False    C    Cherbourg   yes  False
2  woman       False  NaN  Southampton   yes   True
3  woman       False    C  Southampton   yes  False
4    man        True  NaN  Southampton    no   True


   survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third
1         1       1  female  38.0      1      0  71.2833        C  First
2         1       3  female  26.0      0      0   7.9250        S  Third
3         1       1  female  35.0      1      0  53.1000        S  First
4         0       3    male  35.0      0      0   8.0500        S  Third

   adult_male deck  embark_town alive  alone
0        True  NaN  Southampton    no  False
1       False    C    Cherbourg   yes  False
2       False  NaN  Southampton   yes   True
3       False    C  Southampton   yes  False
4        True  NaN  Southampton    no   True

In [38]:
# to drop a particular row
df2.drop(0 , axis = 0 , inplace = True)  # dropping first row

In [39]:
# how to set a new index 
df3 = pd.read_csv("titanic.csv")
print(df3.head(3))
print("\n")
df3.set_index("age" , inplace = True)
print(df3.head(3))

''' 
      survived  pclass     sex  sibsp  parch     fare embarked  class    who  \
age                                                                            
22.0         0       3    male      1      0   7.2500        S  Third    man   
38.0         1     1    female      1      0  71.2833        C  First       woman


Now > row1 is known by index 22.0 and row2 is known by index 38.0
'''
# lets access row with index 38.0
print(df3.loc[38.0])

   survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third
1         1       1  female  38.0      1      0  71.2833        C  First
2         1       3  female  26.0      0      0   7.9250        S  Third

     who  adult_male deck  embark_town alive  alone
0    man        True  NaN  Southampton    no  False
1  woman       False    C    Cherbourg   yes  False
2  woman       False  NaN  Southampton   yes   True


      survived  pclass     sex  sibsp  parch     fare embarked  class    who  \
age
22.0         0       3    male      1      0   7.2500        S  Third    man
38.0         1       1  female      1      0  71.2833        C  First  woman
26.0         1       3  female      0      0   7.9250        S  Third  woman

      adult_male deck  embark_town alive  alone
age
22.0        True  NaN  Southampton    no  False
38.0       False    C    Cherbourg   yes  False
26.0       False  NaN  Southampton   yes   True
      survived  pclass     sex  sibsp  parch      fare embarked   class  \
age
38.0         1       1  female      1      0   71.2833        C   First
38.0         1       3  female      1      5   31.3875        S   Third
38.0         1       1  female      0      0   80.0000      NaN   First
38.0         0       3    male      0      0    7.8958        S   Third
38.0         1       1    male      1      0   90.0000        S   First
38.0         0       1    male      0      1  153.4625        S   First
38.0         0       2  female      0      0   13.0000        S  Second
38.0         0       3    male      0      0    7.0500        S   Third
38.0         0       3    male      0      0    8.6625        S   Third
38.0         1       1  female      0      0  227.5250        C   First
38.0         0       1    male      0      0    0.0000        S   First

        who  adult_male deck  embark_town alive  alone
age
38.0  woman       False    C    Cherbourg   yes  False
38.0  woman       False  NaN  Southampton   yes  False
38.0  woman       False    B          NaN   yes   True
38.0    man        True  NaN  Southampton    no   True
38.0    man        True    C  Southampton   yes  False
38.0    man        True    C  Southampton    no  False
38.0  woman       False  NaN  Southampton    no   True
38.0    man        True  NaN  Southampton    no   True
38.0    man        True  NaN  Southampton    no   True
38.0  woman       False    C    Cherbourg   yes   True
38.0    man        True  NaN  Southampton    no   True

In [40]:
# continue of block 6 : 
# now lets reset the index to default integer index
df3.reset_index(inplace = True)
print(df3.head(3))

    age  survived  pclass     sex  sibsp  parch     fare embarked  class  \
0  22.0         0       3    male      1      0   7.2500        S  Third
1  38.0         1       1  female      1      0  71.2833        C  First
2  26.0         1       3  female      0      0   7.9250        S  Third

     who  adult_male deck  embark_town alive  alone
0    man        True  NaN  Southampton    no  False
1  woman       False    C    Cherbourg   yes  False
2  woman       False  NaN  Southampton   yes   True

In [41]:
# making a dataframe from dictionary
data_list = {
    'Name' : ['Alice' , 'Bob' , 'Charlie' , 'David'],
    'Age' : [24 , 27 , 22 , 32],
    'City' : ['New York' , 'Los Angeles' , 'Chicago' , 'Houston']
}

df_dict = pd.DataFrame(data_list)
print(df_dict)

#instead of list lets use tupple 
data_tupple = {
    'Name' : ('Alice' , 'Bob' , 'Charlie' , 'David'),
    'Age' : (24 , 27 , 22 , 32),
    'City' : ('New York' , 'Los Angeles' , 'Chicago' , 'Houston')
}
df_dict2 = pd.DataFrame(data_tupple)
print(df_dict2)

#using numpy arrays
import numpy as np  
data_numpy = {
    'Name' : np.array(['Alice' , 'Bob' , 'Charlie' , 'David']),
    'Age' : np.array([24 , 27 , 22 , 32]),
    'City' : np.array(['New York' , 'Los Angeles' , 'Chicago' , 'Houston'])
}
df_dict3 = pd.DataFrame(data_numpy)
print(df_dict3)

      Name  Age         City
0    Alice   24     New York
1      Bob   27  Los Angeles
2  Charlie   22      Chicago
3    David   32      Houston
      Name  Age         City
0    Alice   24     New York
1      Bob   27  Los Angeles
2  Charlie   22      Chicago
3    David   32      Houston
      Name  Age         City
0    Alice   24     New York
1      Bob   27  Los Angeles
2  Charlie   22      Chicago
3    David   32      Houston

In [42]:
# how to see null values in dataframe
df4 = pd.read_csv("titanic.csv")
print(df4.isnull().sum()) # gives count of null values in each column
# so either we can drop those null values or we can fill them with some value ( imputation )

# 1. Dropping null values
print(f"before dropping null values: shape : {df4.shape}")
df4.dropna(inplace = True)  # drops all rows which have at least one null value
print(df4.isnull().sum())  # now it will show 0 null values in
print(f"after dropping null values: shape : {df4.shape}")

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64
before dropping null values: shape : (891, 15)
survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       0
class          0
who            0
adult_male     0
deck           0
embark_town    0
alive          0
alone          0
dtype: int64
after dropping null values: shape : (182, 15)

In [43]:
# if we put axis = 1 then it will drop all columns which have at least one null value
df5 = pd.read_csv("titanic.csv")
print(f"before dropping null values: shape : {df5.shape}")
df5.dropna(axis = 1 , inplace = True)  # drops all columns which have at least one null value
print(f"after dropping null values: shape : {df5.shape}")

before dropping null values: shape : (891, 15)
after dropping null values: shape : (891, 11)

In [44]:
import pandas as pd

# read the file
df6 = pd.read_csv("titanic.csv")
print(df6.shape)

# drop rows with null values in 'age'
df6.dropna(subset=['age'], inplace=True)

# OR to drop the entire column 'age':
# df6.drop(columns=['age'], inplace=True)
print(df6.shape)

(891, 15)
(714, 15)

In [45]:
#imputation of missing values >> replacing mussing values with some value
#numberical columns >> we can replace missing values with mean , median
# before that we have to remove outliers then only mean and median will be useful


#categorical columns >> we can replace missing values with mode (most frequent value) mode
df7 = pd.read_csv("titanic.csv")
print(df7.isnull().sum())

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [46]:
# replacing missing value with some conastant value")
#df7['embarked'].fillna('S' , inplace = True)  # replacing missing values in 'embarked' column with 'S'
df7.fillna(0, inplace=True)
print(df7.isnull().sum())

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       0
class          0
who            0
adult_male     0
deck           0
embark_town    0
alive          0
alone          0
dtype: int64

In [47]:
df8 = pd.read_csv("Sample_null_value.csv")
print(df8)

# df8['Age'].fillna(df8['Age'].mean() , inplace = True) # this is the older verson
df8.fillna({
    'Age': df8['Age'].mean(),             # replace missing Age with mean
    'Salary': df8['Salary'].median(),     # replace missing Salary with median
    'Department': df8['Department'].mode()[0]  # replace missing Department with mode (most frequent)
}, inplace=True)

print(df8)

      Name   Age   Salary Department  Experience
0    Alice  25.0  50000.0         HR         2.0
1      Bob   NaN  54000.0         IT         4.0
2  Charlie  30.0      NaN        NaN         NaN
3    David  22.0  58000.0    Finance         3.0
4      Eve   NaN  60000.0    Finance         5.0
5    Frank  29.0      NaN         HR         6.0
6    Grace  31.0  62000.0         IT         NaN
7     Hank   NaN  64000.0        NaN         8.0
8      Ivy  27.0      NaN    Finance        10.0
9     Jack  35.0  70000.0         HR         NaN
      Name        Age   Salary Department  Experience
0    Alice  25.000000  50000.0         HR         2.0
1      Bob  28.428571  54000.0         IT         4.0
2  Charlie  30.000000  60000.0    Finance         NaN
3    David  22.000000  58000.0    Finance         3.0
4      Eve  28.428571  60000.0    Finance         5.0
5    Frank  29.000000  60000.0         HR         6.0
6    Grace  31.000000  62000.0         IT         NaN
7     Hank  28.428571  64000.0    Finance         8.0
8      Ivy  27.000000  60000.0    Finance        10.0
9     Jack  35.000000  70000.0         HR         NaN

In [48]:
#ffill concept : it says to fill the missing value with previous value in that column
df9 = pd.read_csv("Sample_null_value.csv")
print(df9)
print("\n\nAfter applying ffill method\n")
df9.fillna(method = 'ffill' , inplace = True)
print(df9)

# NOTE: If the first value(s) in a column are NaN, ffill will not fill them since there is no previous value to carry forward.

      Name   Age   Salary Department  Experience
0    Alice  25.0  50000.0         HR         2.0
1      Bob   NaN  54000.0         IT         4.0
2  Charlie  30.0      NaN        NaN         NaN
3    David  22.0  58000.0    Finance         3.0
4      Eve   NaN  60000.0    Finance         5.0
5    Frank  29.0      NaN         HR         6.0
6    Grace  31.0  62000.0         IT         NaN
7     Hank   NaN  64000.0        NaN         8.0
8      Ivy  27.0      NaN    Finance        10.0
9     Jack  35.0  70000.0         HR         NaN


After applying ffill method

      Name   Age   Salary Department  Experience
0    Alice  25.0  50000.0         HR         2.0
1      Bob  25.0  54000.0         IT         4.0
2  Charlie  30.0  54000.0         IT         4.0
3    David  22.0  58000.0    Finance         3.0
4      Eve  22.0  60000.0    Finance         5.0
5    Frank  29.0  60000.0         HR         6.0
6    Grace  31.0  62000.0         IT         6.0
7     Hank  31.0  64000.0         IT         8.0
8      Ivy  27.0  64000.0    Finance        10.0
9     Jack  35.0  70000.0         HR        10.0

C:\Users\Naman\AppData\Local\Temp\ipykernel_13716\4214396269.py:5: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df9.fillna(method = 'ffill' , inplace = True)

In [49]:
# bfill concept : it says to fill the missing value with next value in that column
df10 = pd.read_csv("Sample_null_value.csv") 
print("\n\nBefore applying bfill method\n")
print(df10)
df10.fillna(method = 'bfill' , inplace = True)
print("\n\nAfter applying bfill method\n")
print(df10)
#NOTE: If the last value(s) in a column are NaN, bfill will not fill them since there is no next value to carry backward.

Before applying bfill method

      Name   Age   Salary Department  Experience
0    Alice  25.0  50000.0         HR         2.0
1      Bob   NaN  54000.0         IT         4.0
2  Charlie  30.0      NaN        NaN         NaN
3    David  22.0  58000.0    Finance         3.0
4      Eve   NaN  60000.0    Finance         5.0
5    Frank  29.0      NaN         HR         6.0
6    Grace  31.0  62000.0         IT         NaN
7     Hank   NaN  64000.0        NaN         8.0
8      Ivy  27.0      NaN    Finance        10.0
9     Jack  35.0  70000.0         HR         NaN


After applying bfill method

      Name   Age   Salary Department  Experience
0    Alice  25.0  50000.0         HR         2.0
1      Bob  30.0  54000.0         IT         4.0
2  Charlie  30.0  58000.0    Finance         3.0
3    David  22.0  58000.0    Finance         3.0
4      Eve  29.0  60000.0    Finance         5.0
5    Frank  29.0  62000.0         HR         6.0
6    Grace  31.0  62000.0         IT         8.0
7     Hank  27.0  64000.0    Finance         8.0
8      Ivy  27.0  70000.0    Finance        10.0
9     Jack  35.0  70000.0         HR         NaN

C:\Users\Naman\AppData\Local\Temp\ipykernel_13716\902903683.py:5: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df10.fillna(method = 'bfill' , inplace = True)

Questions

In [50]:
# Que 1: what is the average fare paid by the people who survived ? titanic.csv
df11 = pd.read_csv("titanic.csv")
print(df11.head(3))
print("\n")

print(df11[df11['survived'] == 1].head(3))

avg_fare = df11[df11['survived'] == 1]['fare'].mean()
print(f"The average fare paid by the people who survived is: {avg_fare}")

   survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third
1         1       1  female  38.0      1      0  71.2833        C  First
2         1       3  female  26.0      0      0   7.9250        S  Third

     who  adult_male deck  embark_town alive  alone
0    man        True  NaN  Southampton    no  False
1  woman       False    C    Cherbourg   yes  False
2  woman       False  NaN  Southampton   yes   True


   survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
1         1       1  female  38.0      1      0  71.2833        C  First
2         1       3  female  26.0      0      0   7.9250        S  Third
3         1       1  female  35.0      1      0  53.1000        S  First

     who  adult_male deck  embark_town alive  alone
1  woman       False    C    Cherbourg   yes  False
2  woman       False  NaN  Southampton   yes   True
3  woman       False    C  Southampton   yes  False
The average fare paid by the people who survived is: 48.39540760233918

In [51]:
#  we will be use groupby function

print(df11.groupby('survived').mean(numeric_only=True))
# working of groupby function:
# first it will divide the dataframe into two parts where survived = 0 and survived = 1
# then it will calculate mean of each column for both parts and give the result

            pclass        age     sibsp     parch       fare  adult_male  \
survived
0         2.531876  30.626179  0.553734  0.329690  22.117887    0.817851
1         1.950292  28.343690  0.473684  0.464912  48.395408    0.257310

             alone
survived
0         0.681239
1         0.476608

In [52]:
#lets use aggrigate function with groupby
import pandas as pd
import numpy as np
df12 = pd.read_csv("titanic.csv")
print(df12.groupby('survived').agg({
    'age': ['mean', 'median', 'min', 'max'],
    'fare': ['mean', 'median', 'min', 'max'],
    'pclass': 'count'
}))

# for std : np.std will be used
# print(df12.groupby('survived').agg({
#     'age': np.std,
#     'fare': np.std
# }))

                age                          fare                       pclass
               mean median   min   max       mean median  min       max  count
survived
0         30.626179   28.0  1.00  74.0  22.117887   10.5  0.0  263.0000    549
1         28.343690   28.0  0.42  80.0  48.395408   26.0  0.0  512.3292    342

In [53]:
# how many passengers survived / not survived for each sex and pclass 
df13 = pd.read_csv("titanic.csv") 
print(df13.groupby(['sex', 'pclass', 'survived']).size())

# how groupby works here:
# first it will divide the dataframe into multiple parts based on unique combinations of 'sex' , 'pclass' and 'survived'
# then it will count number of rows in each part and give the result

sex     pclass  survived
female  1       0             3
                1            91
        2       0             6
                1            70
        3       0            72
                1            72
male    1       0            77
                1            45
        2       0            91
                1            17
        3       0           300
                1            47
dtype: int64

In [54]:
# convert the above groupby result into a dataframe
df_grouped = df13.groupby(['sex', 'pclass', 'survived']).size().reset_index(name='count')
print(df_grouped)

       sex  pclass  survived  count
0   female       1         0      3
1   female       1         1     91
2   female       2         0      6
3   female       2         1     70
4   female       3         0     72
5   female       3         1     72
6     male       1         0     77
7     male       1         1     45
8     male       2         0     91
9     male       2         1     17
10    male       3         0    300
11    male       3         1     47

In [55]:
# we can also use to_frame 
df_grouped = df13.groupby(['sex', 'pclass', 'survived']).size().to_frame(name='count').reset_index()
print(df_grouped)

       sex  pclass  survived  count
0   female       1         0      3
1   female       1         1     91
2   female       2         0      6
3   female       2         1     70
4   female       3         0     72
5   female       3         1     72
6     male       1         0     77
7     male       1         1     45
8     male       2         0     91
9     male       2         1     17
10    male       3         0    300
11    male       3         1     47

In [56]:
df_grouped.T # transpose of dataframe

,0,1,2,3,4,5,6,7,8,9,10,11
sex,female,female,female,female,female,female,male,male,male,male,male,male
pclass,1,1,2,2,3,3,1,1,2,2,3,3
survived,0,1,0,1,0,1,0,1,0,1,0,1
count,3,91,6,70,72,72,77,45,91,17,300,47

In [57]:
df_grouped = df13.groupby(['sex', 'pclass'])['survived'].size().to_frame(name='count').reset_index()
print(df_grouped)

      sex  pclass  count
0  female       1     94
1  female       2     76
2  female       3    144
3    male       1    122
4    male       2    108
5    male       3    347