In [1]:
import pandas as pd
df1 = pd.read_csv("titanic.csv")
print(df1.head())

   survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third
1         1       1  female  38.0      1      0  71.2833        C  First
2         1       3  female  26.0      0      0   7.9250        S  Third
3         1       1  female  35.0      1      0  53.1000        S  First
4         0       3    male  35.0      0      0   8.0500        S  Third

     who  adult_male deck  embark_town alive  alone
0    man        True  NaN  Southampton    no  False
1  woman       False    C    Cherbourg   yes  False
2  woman       False  NaN  Southampton   yes   True
3  woman       False    C  Southampton   yes  False
4    man        True  NaN  Southampton    no   True

In [ ]:
df1[0:100] # first 100 rows >> similar as string slicing

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,0,3,male,NaN,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
96,0,1,male,71.0,0,0,34.6542,C,First,man,True,A,Cherbourg,no,True
97,1,1,male,23.0,0,1,63.3583,C,First,man,True,D,Cherbourg,yes,False
98,1,2,female,34.0,0,1,23.0000,S,Second,woman,False,NaN,Southampton,yes,False
99,0,2,male,34.0,1,0,26.0000,S,Second,man,True,NaN,Southampton,no,False

In [3]:
#every fifth row 
df1[0:100:5]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
10,1,3,female,4.0,1,1,16.7000,S,Third,child,False,G,Southampton,yes,False
15,1,2,female,55.0,0,0,16.0000,S,Second,woman,False,NaN,Southampton,yes,True
20,0,2,male,35.0,0,0,26.0000,S,Second,man,True,NaN,Southampton,no,True
25,1,3,female,38.0,1,5,31.3875,S,Third,woman,False,NaN,Southampton,yes,False
30,0,1,male,40.0,0,0,27.7208,C,First,man,True,NaN,Cherbourg,no,True
35,0,1,male,42.0,1,0,52.0000,S,First,man,True,NaN,Southampton,no,False
40,0,3,female,40.0,1,0,9.4750,S,Third,woman,False,NaN,Southampton,no,False
45,0,3,male,NaN,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
50,0,3,male,7.0,4,1,39.6875,S,Third,child,False,NaN,Southampton,no,False
55,1,1,male,NaN,0,0,35.5000,S,First,man,True,C,Southampton,yes,True
60,0,3,male,22.0,0,0,7.2292,C,Third,man,True,NaN,Cherbourg,no,True
65,1,3,male,NaN,1,1,15.2458,C,Third,man,True,NaN,Cherbourg,yes,False
70,0,2,male,32.0,0,0,10.5000,S,Second,man,True,NaN,Southampton,no,True
75,0,3,male,25.0,0,0,7.6500,S,Third,man,True,F,Southampton,no,True
80,0,3,male,22.0,0,0,9.0000,S,Third,man,True,NaN,Southampton,no,True
85,1,3,female,33.0,3,0,15.8500,S,Third,woman,False,NaN,Southampton,yes,False
90,0,3,male,29.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
95,0,3,male,NaN,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [4]:
# accessing rows and columns of dataframe >> implicit/integer/internal indexing  explecit or named indexing

In [5]:
#Implesit indexing
#iloc[row_indexer , column_indexer]
df1.iloc[0:5 , 0:3]  # first 5 rows and first 3 columns

   survived  pclass     sex
0         0       3    male
1         1       1  female
2         1       3  female
3         1       1  female
4         0       3    male

In [10]:
# Explicit indexing
#loc[row_indexer , column_indexer]
print(df1.loc[0:4 , ["age" , "fare"]])  # first 5 rows and age , fare columns
print("\n \n \n")
print(list(df1.loc[0:4 , ["age" , "fare"]] .itertuples()))

    age     fare
0  22.0   7.2500
1  38.0  71.2833
2  26.0   7.9250
3  35.0  53.1000
4  35.0   8.0500




[Pandas(Index=0, age=22.0, fare=7.25), Pandas(Index=1, age=38.0, fare=71.2833), Pandas(Index=2, age=26.0, fare=7.925), Pandas(Index=3, age=35.0, fare=53.1), Pandas(Index=4, age=35.0, fare=8.05)]

In [19]:

series_one = pd.Series(list(df1['age'][2:5]), index=['a', 'b', 'c'])
series_two = pd.Series(list(df1['age'][5:8]), index = ['row5', 'row6', 'row7'])
print(series_one)
print("\n")
print(series_two)

# concatenate two series: >> series with different indexes and dataferame can not be concatenated directly using '+'
# if you keep the indexes same then it will work
series_three = pd.Series(list(df1['age'][2:5]), index=['row5', 'row6', 'row7'])
print("\n")
print(series_three)
print("\n")
print(series_two + series_three)  # it will add values of same index and for different index it will give NaN

a    26.0
b    35.0
c    35.0
dtype: float64


row5     NaN
row6    54.0
row7     2.0
dtype: float64


row5    26.0
row6    35.0
row7    35.0
dtype: float64


row5     NaN
row6    89.0
row7    37.0
dtype: float64

In [2]:
#drop rows and columns
# by default if you drop anything pandas assume you are dropping rows axis=0

import pandas as pd
df2 = pd.read_csv("titanic.csv")
print(df2.head())
print("\n")

# lets say we have to drop 'who' column 
# df2.drop("who") => gives you error because by default it will try to drop row with index 'who' which is not present
# to drop 'who' column we have to do axix = 1 
df2.drop("who" , axis = 1 , inplace = True)  # inplace = True means changes will be made in original dataframe
# so => axis = 0 >> rows
#    => axis = 1 >> columns
# inplace = True >> changes will be made in original dataframe
print(df2.head())

   survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third
1         1       1  female  38.0      1      0  71.2833        C  First
2         1       3  female  26.0      0      0   7.9250        S  Third
3         1       1  female  35.0      1      0  53.1000        S  First
4         0       3    male  35.0      0      0   8.0500        S  Third

     who  adult_male deck  embark_town alive  alone
0    man        True  NaN  Southampton    no  False
1  woman       False    C    Cherbourg   yes  False
2  woman       False  NaN  Southampton   yes   True
3  woman       False    C  Southampton   yes  False
4    man        True  NaN  Southampton    no   True


   survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third
1         1       1  female  38.0      1      0  71.2833        C  First
2         1       3  female  26.0      0      0   7.9250        S  Third
3         1       1  female  35.0      1      0  53.1000        S  First
4         0       3    male  35.0      0      0   8.0500        S  Third

   adult_male deck  embark_town alive  alone
0        True  NaN  Southampton    no  False
1       False    C    Cherbourg   yes  False
2       False  NaN  Southampton   yes   True
3       False    C  Southampton   yes  False
4        True  NaN  Southampton    no   True

In [ ]:
# to drop a particular row
df2.drop(0 , axis = 0 , inplace = True)  # dropping first row

In [6]:
# how to set a new index 
df3 = pd.read_csv("titanic.csv")
print(df3.head(3))
print("\n")
df3.set_index("age" , inplace = True)
print(df3.head(3))

''' 
      survived  pclass     sex  sibsp  parch     fare embarked  class    who  \
age                                                                            
22.0         0       3    male      1      0   7.2500        S  Third    man   
38.0         1     1    female      1      0  71.2833        C  First       woman


Now > row1 is known by index 22.0 and row2 is known by index 38.0
'''
# lets access row with index 38.0
print(df3.loc[38.0])

   survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third
1         1       1  female  38.0      1      0  71.2833        C  First
2         1       3  female  26.0      0      0   7.9250        S  Third

     who  adult_male deck  embark_town alive  alone
0    man        True  NaN  Southampton    no  False
1  woman       False    C    Cherbourg   yes  False
2  woman       False  NaN  Southampton   yes   True


      survived  pclass     sex  sibsp  parch     fare embarked  class    who  \
age
22.0         0       3    male      1      0   7.2500        S  Third    man
38.0         1       1  female      1      0  71.2833        C  First  woman
26.0         1       3  female      0      0   7.9250        S  Third  woman

      adult_male deck  embark_town alive  alone
age
22.0        True  NaN  Southampton    no  False
38.0       False    C    Cherbourg   yes  False
26.0       False  NaN  Southampton   yes   True
      survived  pclass     sex  sibsp  parch      fare embarked   class  \
age
38.0         1       1  female      1      0   71.2833        C   First
38.0         1       3  female      1      5   31.3875        S   Third
38.0         1       1  female      0      0   80.0000      NaN   First
38.0         0       3    male      0      0    7.8958        S   Third
38.0         1       1    male      1      0   90.0000        S   First
38.0         0       1    male      0      1  153.4625        S   First
38.0         0       2  female      0      0   13.0000        S  Second
38.0         0       3    male      0      0    7.0500        S   Third
38.0         0       3    male      0      0    8.6625        S   Third
38.0         1       1  female      0      0  227.5250        C   First
38.0         0       1    male      0      0    0.0000        S   First

        who  adult_male deck  embark_town alive  alone
age
38.0  woman       False    C    Cherbourg   yes  False
38.0  woman       False  NaN  Southampton   yes  False
38.0  woman       False    B          NaN   yes   True
38.0    man        True  NaN  Southampton    no   True
38.0    man        True    C  Southampton   yes  False
38.0    man        True    C  Southampton    no  False
38.0  woman       False  NaN  Southampton    no   True
38.0    man        True  NaN  Southampton    no   True
38.0    man        True  NaN  Southampton    no   True
38.0  woman       False    C    Cherbourg   yes   True
38.0    man        True  NaN  Southampton    no   True

In [7]:
# continue of block 6 : 
# now lets reset the index to default integer index
df3.reset_index(inplace = True)
print(df3.head(3))

    age  survived  pclass     sex  sibsp  parch     fare embarked  class  \
0  22.0         0       3    male      1      0   7.2500        S  Third
1  38.0         1       1  female      1      0  71.2833        C  First
2  26.0         1       3  female      0      0   7.9250        S  Third

     who  adult_male deck  embark_town alive  alone
0    man        True  NaN  Southampton    no  False
1  woman       False    C    Cherbourg   yes  False
2  woman       False  NaN  Southampton   yes   True

In [9]:
# making a dataframe from dictionary
data_list = {
    'Name' : ['Alice' , 'Bob' , 'Charlie' , 'David'],
    'Age' : [24 , 27 , 22 , 32],
    'City' : ['New York' , 'Los Angeles' , 'Chicago' , 'Houston']
}

df_dict = pd.DataFrame(data_list)
print(df_dict)

#instead of list lets use tupple 
data_tupple = {
    'Name' : ('Alice' , 'Bob' , 'Charlie' , 'David'),
    'Age' : (24 , 27 , 22 , 32),
    'City' : ('New York' , 'Los Angeles' , 'Chicago' , 'Houston')
}
df_dict2 = pd.DataFrame(data_tupple)
print(df_dict2)

#using numpy arrays
import numpy as np  
data_numpy = {
    'Name' : np.array(['Alice' , 'Bob' , 'Charlie' , 'David']),
    'Age' : np.array([24 , 27 , 22 , 32]),
    'City' : np.array(['New York' , 'Los Angeles' , 'Chicago' , 'Houston'])
}
df_dict3 = pd.DataFrame(data_numpy)
print(df_dict3)

      Name  Age         City
0    Alice   24     New York
1      Bob   27  Los Angeles
2  Charlie   22      Chicago
3    David   32      Houston
      Name  Age         City
0    Alice   24     New York
1      Bob   27  Los Angeles
2  Charlie   22      Chicago
3    David   32      Houston
      Name  Age         City
0    Alice   24     New York
1      Bob   27  Los Angeles
2  Charlie   22      Chicago
3    David   32      Houston

In [ ]:
# taxonamy.csv